auth0:
  domain: your-domain-oauth0
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${auth0.domain}/
          jwk-set-uri: https://${auth0.domain}/.well-known/openid-configuration
  datasource:
    url: jdbc:mysql://localhost:3306/genealogictree_db?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: 12345  # Para Scooby = 123456, Para Catatau = 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8080
genealogictree:
  config:
    initial-layer: 0
  logs:
    send-splunk: "SEND_SPLUNK"

