spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration #depois deve apagar quando colocar segurança na aplicação
  datasource:
    url: jdbc:mysql://localhost:3306/genealogictree_db?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: 12345  # Para Scooby = 123456, Para Catatau = 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8080

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration